### ISSUE TITLE
incomplete Gerber files

### ISSUE THREAD

**Issue by stkdiretto** [IRNAS/KORUZA#2]
All gerber folders save the RPI shield one are missing the respective GKO file, which make panelizing the boards impossible for me (using gerbertools).

I'd export the gerbers anew, but alas, the sources are Altium and not KiCAD, so I can't :(

**Comment by SloMusti** [comment]
Layer GM3 contains the outline you require, simply rename it to GKO and it shall serve your purpose.

Also: See KORUZA Pro electronics if that may server your purpose better. https://github.com/IRNAS/KORUZA-Pro

**Comment by stkdiretto** [comment]
Thank you, this solved the problem
